config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'events#index'
  resources :users, only: [:index, :edit, :update]
  resources :my_calendars, only: [:new, :create,:index, :edit, :update] do
    resources :events, only: [:index, :edit, :update,:new, :create,:destroy]
  end
  resources :events, only: [:index, :edit, :update,:new, :create,:destroy]
  resources :shares, only: [:new, :create,:index, :edit, :update] do
    resources :events, only: [:index, :edit, :update,:new, :create,:destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calendar.rb
class Calendar < ApplicationRecord
  has_many :calendar_users
  has_many :users, through: :calendar_users
  validates :name, presence: true, uniqueness: true
end

app/models/calendar_user.rb
class CalendarUser < ApplicationRecord
  belongs_to :my_calendar
  belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :my_calendar
  belongs_to :share
  belongs_to :user
end

app/models/my_calendar.rb
class MyCalendar < ApplicationRecord
  has_many :my_calendar_users
  has_many :users, through: :my_calendar_users
  has_many :events
  
  validates :name, presence: true, uniqueness: true
end

app/models/my_calendar_user.rb
class MyCalendarUser < ApplicationRecord
  belongs_to :my_calendar
  belongs_to :user
end

app/models/share.rb
class Share < ApplicationRecord
  has_many :share_users
  has_many :users, through: :share_users
  has_many :events

  validates :name, presence: true, uniqueness: true
end

app/models/share_user.rb
class ShareUser < ApplicationRecord
  belongs_to :share
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :my_calendar_users
  has_many :share_users
  has_many :shares, through: :share_users
  has_many :my_calendars, through: :my_calendar_users
  has_many :events

  validates :name,presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:title, :body, :start_date, :end_date)
    end
end

app/controllers/my_calendars_controller.rb
class MyCalendarsController < ApplicationController

  def index
    
  end

  def new
    @my_calendar = MyCalendar.new
    @my_calendar.users << current_user
  end

  def create
    @my_calendar = MyCalendar.new(my_calendar_params)
    if @my_calendar.save
      redirect_to root_path, notice: 'カレンダーを作成しました'
    else
      render :new
    end
  end

  def edit
    @my_calendar = MyCalendar.find(params[:id])
  end
  
  def update
    @my_calendar = MyCalendar.find(params[:id])
    if @my_calendar.update(my_calendar_params)
      redirect_to root_path, notice: 'カレンダーを更新しました'
    else
      render :edit
    end
  end
  private
  def my_calendar_params
    params.require(:my_calendar).permit(:name, user_ids: [])
  end
end

app/controllers/shares_controller.rb
class SharesController < ApplicationController
  def index
       
  end
  def new
    @share = Share.new
    @share.users << current_user
  end

  def create
    @share = Share.new(share_params)
    if @share.save
      redirect_to root_path, notice: 'カレンダーを作成しました'
    else
      render :new
    end
  end

  def edit
    @share = Share.find(params[:id])
  end
  
  def update
    @share = Share.find(params[:id])
    if @share.update(share_params)
      redirect_to root_path, notice: 'カレンダーを更新しました'
    else
      render :edit
    end
  end
  private
  def share_params
    params.require(:share).permit(:name, user_ids: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    
  end
  
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name,:email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_dialog.html.haml
#event-dialog
  .dialog-content
    = form_with(model: @event, local: true) do |form|
      .field
        = form.label :title
        = form.text_field :title, placeholder: "タイトルを追加", autofocus: true
      .field
        = form.label :body
        = form.text_field :body
      .field
        = form.label :start_date
        = form.datetime_select :start_date
      .field
        = form.label :end_date
        = form.datetime_select :end_date
      .actions
        = form.submit
  %a#dialog-close.button-link
    閉じる

app/views/events/_new_event.html.haml
.New-event
  .box
    %button.add-event{onfocus: "this.blur();"}
      %i.fas.fa-plus.add
  .new-contents
    コンテンツ
    .close-btn
      close
.main
  .main-cover

.New-event
  .add-event
  .
  
:javascript
  var toggleBtn = document.querySelector('.add-event');
  var sidebar = document.querySelector('.New-event');
  toggleBtn.addEventListener('click', function() {
    toggleBtn.classList.toggle('btn-closed');
    sidebar.classList.toggle('btn-closed');
    if($("#new-overlay")[0]) return false ;
      $("body").append('<div id="new-overlay"></div>');
      $("#new-overlay").fadeIn("normal");
      $("#new-overlay").unbind().click(function(){
        sidebar.classList.toggle('btn-closed');
        $("#new-overlay").fadeOut("slow",function(){
          $("#new-overlay").remove();
        });
       });
  })


  $(function(){
  var modalBtn = $('.add-event');
  var modalBtnClose = $('.close-btn');
  var modalBtnCloseFix = $('.js-modal__btn--close--fix');
  var modalBg = $('.js-modal__bg');
  var modalMain = $('.js-modal__main');
  modalBtn.on('click', function (e) {
    $(this).next(modalBg).fadeIn();
    $(this).next(modalBg).next(modalMain).removeClass("_slideDown");
    $(this).next(modalBg).next(modalMain).addClass("_slideUp");
  });
  modalBtnClose.on('click', function (e) {
    modalBg.fadeOut();
    modalMain.removeClass("_slideUp");
    modalMain.addClass("_slideDown");
  });
  modalBtnCloseFix.on('click', function (e) {
    modalBg.fadeOut();
    modalMain.removeClass("_slideUp");
    modalMain.addClass("_slideDown");
  });
  modalMain.on('click', function (e) {
    e.stopPropagation();
  });
  modalBg.on('click', function () {
    $(this).fadeOut();
    $(this).next(modalMain).removeClass("_slideUp");
    $(this).next(modalMain).addClass("_slideDown");
  });
});

app/views/events/_side_bar.html.haml
.Side-bar
  .Item
    %head
      .Item__btn
        .item-title
          %a{data: {toggle: "collapse"}, 
                    href:"#Item-list",
                    role:"button", 
                    aria: {expanded:"false"}, 
                    aria:{controls:"collapseExample"},
                    class: "bar-btn"}
            = icon('fas', "bars")
    %body
      #Item-list.collapse.navbar-collapse
        .menu-bar
          .top
            .icon-list
              = link_to edit_user_path(current_user), class: "icons" do
                = icon('fas', "cog", class: 'edit')
          %ul.menu
            %li.menu__calendar-name
              dog
            %li.menu__calendar-name
              child
      %script{crossorigin: "anonymous", integrity: "sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1", src: "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"}
      %script{crossorigin: "anonymous", integrity: "sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM", src: "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"}

app/views/events/_sidebar.html.haml
.sidebar
  %ul.tab
    %li.slide#User-bar
      %button.sidebar-toggle#user{onfocus: "this.blur();"}
        %i.fas.fa-bars.icon#user-icon
      .contents
        .contents__box
          .user-name
            = current_user.name
          .edit-user
            = link_to edit_user_path(current_user), class: "menu__icons" do
              = icon('fas', "cog", class: 'edit')
          
    %li.slide#My-bar
      %button.sidebar-toggle#my{onfocus: "this.blur();"}
        %i.fas.fa-user-alt.icon#my-icon
      .contents
        - current_user.my_calendars.each do |my_calendar|
          .contents__box
            = link_to my_calendar_events_path(my_calendar) do
              .calendar-name
                = my_calendar.name
              .calendar-edit
                =link_to edit_my_calendar_path(my_calendar), class:"editlink" do
                  = icon('fas','pen',class:"edit-icon")
        .create-calendar
          = link_to new_my_calendar_path, class:"add-calendar" do
            + カレンダー作成
    %li.slide#Share-bar
      %button.sidebar-toggle#share{onfocus: "this.blur();"}
        %i.fas.fa-users.icon#share-icon
      .contents
        - current_user.shares.each do |share|
          .contents__box
            = link_to share_events_path(share) do
              .calendar-name
                = share.name
              .calendar-edit
                =link_to edit_share_path(share), class:"editlink" do
                  = icon('fas','pen',class:"edit-icon")
        .create-calendar
          = link_to new_share_path, class:"add-calendar" do
            + カレンダー作成

:javascript
  $("ul li").on("click",function(){
    $(this).toggleClass("is-closed");
  });

app/views/events/index.html.haml
%table
  .wrapper
    = render "sidebar"
    #calendar
    = render "dialog"
  = render "mycalendars-name"
    
%br/

app/views/events/new.html.haml
#event-dialog
  .dialog-content
    = form_with(model: @event, local: true) do |form|
      .field
        = form.label :title, 'タイトル'
        = form.text_field :title
      .field
        = form.label :body
        = form.text_field :body
      .field
        = form.label :start_date
        = form.datetime_select :start_date
      .field
        = form.label :end_date
        = form.datetime_select :end_date
      .actions
        = form.submit
  %a#dialog-close.button-link
    閉じる

app/views/layouts/_notifications.html.haml
.Notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Shareschedule
    %link{href: "https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css",rel:"stylesheet"}/
    %link{href: "https://fonts.googleapis.com/css?family=Kaushan+Script", rel:"stylesheet"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body{"data-turbolinks" => "false"}
    = render 'layouts/notifications'
    = yield

app/views/my_calendars/_form.html.haml
= form_with model: my_calendar, local: true do |f|
  - if my_calendar.errors.any?
    .SettingGroupForm__errors
      %h2= "#{my_calendar.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - my_calendar.errors.full_messages.each do |message|
          %li= message
  .SettingGroupForm__field
    .SettingGroupForm__leftField
      = f.label :name, "カレンダー名", class: 'SettingGroupForm__label'
    .SettingGroupForm__rightField
      = f.text_field :name, class: 'SettingGroupForm__input', placeholder: 'カレンダー名を入力してください'
  .SettingGroupForm__field
    .SettingGroupForm__leftField
      %label.SettingGroupForm__label チャットメンバーを追加
    .SettingGroupForm__rightField
      / グループ作成機能の追加時はここにcollection_check_boxesの記述を入れてください
      = f.collection_check_boxes :user_ids, User.all, :id, :name
      / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
  .SettingGroupForm__field
    .SettingGroupForm__leftField
    .SettingGroupForm__rightField
      = f.submit class: 'SettingGroupForm__button'

app/views/my_calendars/edit.html.haml
.SettingGroupForm
  %h1 カレンダー編集
  = render partial: 'form', locals: { my_calendar: @my_calendar }

app/views/my_calendars/index.html.haml
.wrapper 
  = render 'events/sidebar'
  #calendar
  = render 'events/dialog'
= render "mycalendars-name"

app/views/my_calendars/new.html.haml
.SettingGroupForm
  %h1 新規カレンダー
  = render partial: 'form', locals: { my_calendar: @my_calendar }

app/views/shares/_form.html.haml
= form_with model: share, local: true do |f|
  - if share.errors.any?
    .SettingGroupForm__errors
      %h2.error-word= "#{share.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - share.errors.full_messages.each do |message|
          %li= message
  .SettingGroupForm__field
    .SettingGroupForm__leftField
      = f.label :name, "カレンダー名", class: 'SettingGroupForm__label'
    .SettingGroupForm__rightField
      = f.text_field :name, class: 'SettingGroupForm__input', placeholder: 'カレンダー名を入力してください'
  .SettingGroupForm__field
    .SettingGroupForm__leftField
      %label.SettingGroupForm__label チャットメンバーを追加
    .SettingGroupForm__rightField
      / グループ作成機能の追加時はここにcollection_check_boxesの記述を入れてください
      = f.collection_check_boxes :user_ids, User.all, :id, :name
      / この部分はインクリメンタルサーチ（ユーザー追加の非同期化のときに使用します
  .SettingGroupForm__field
    .SettingGroupForm__leftField
    .SettingGroupForm__rightField
      = f.submit class: 'SettingGroupForm__button'

app/views/shares/_sharecalendar.html.haml
.name #{current_user.shares.find(params[:share_id]).name}

app/views/shares/edit.html.haml
.SettingGroupForm
  %h1 カレンダー編集
  = render partial: 'form', locals: { share: @share }

app/views/shares/index.html.haml
.wrapper 
  = render 'events/sidebar'
  #calendar
= render "sharecalendars-name"

app/views/shares/new.html.haml
.SettingGroupForm
  %h1 新規カレンダー
  = render partial: 'form', locals: { share: @share }

app/views/users/edit.html.haml
.AccountPage
  .AccountPage__title
    %h2 Edit Account
    %h5 アカウントの編集
    = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'Button'
    = link_to "トップページに戻る", :back, class: 'Button'
  .AccountPage__form
    = form_for(current_user) do |f|
      .FormField
        .FormField__label--normal
          = f.label :name
        .FormField__input--normal
          = f.text_field :name, autofocus: true
      .FormField
        .FormField__label--normal
          = f.label :email
        .FormField__input--normal
          = f.email_field :email
      = f.submit "Update", class: 'Button UserButton'